language: python
python:
  - "2.7"
  - "3.3"
install:
  - "pip install Django==1.6.10"
  - "pip install -r tests_requirements.txt"
  - "python setup.py develop"
#  - "pip install coveralls"
script:
  - "python runtests.py"
#  - "coverage run --source=popolo runtests.py"
# after_success:
#  - coverage report -m
#  - coveralls