language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=1.10
install:
  - pip install -q Django==$DJANGO_VERSION
  - "pip install -r tests_requirements.txt"
  - "python setup.py install"
  - "pip install coveralls"
script:
  - "coverage run --source=promises runtests.py"
after_success:
  - coverage report -m
  - coveralls
