language: python
python:
  - "2.7"
install:
  - "pip install Django"
  - "pip install -r tests_requirements.txt"
  - "python setup.py develop"
  - "pip install coveralls"
script:
  - "coverage run --source=promises runtests.py"
after_success:
  - coverage report -m
  - coveralls
