language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.6.10
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.8
install:
  - pip install -q Django==$DJANGO_VERSION
  - "pip install -r tests_requirements.txt"
  - "python setup.py install"
  - "pip install coveralls"
script:
  - "coverage run --source=promises runtests.py"
after_success:
  - coverage report -m
  - coveralls
